export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const FORGOT_PASS = 'FORGOT_PASS'
export const RESET_PASS ='RESET_PASS'
export const UPDATE_PASS = ' UPDATE_PASS'
export const VERIFY_EMAIL = 'VERIFY_EMAIL'
export const LOGOUT_MESSAGE = 'LOGOUT_MESSAGE';

export const REG_USER = 'REG_USER';
export const GET_USER ='GET_USER';
export const DOCTOR_LOGIN_INFO = 'DOCTOR_LOGIN_INFO';
export const COUNT_USERS = 'COUNT_USERS';


export const FETCH_NOTIFICATION_DATA = 'FETCH_NOTIFICATION_DATA';

export const COUNT_WEB_VISITERS = 'COUNT_WEB_VISITERS';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';



export const REG_ADMIN = 'REG_ADMIN';
export const GET_ADMIN = 'GET_ADMIN';
export const APROVE_ADMIN = 'APROVE_ADMIN';
export const PENDING_ADMIN = 'PENDING_ADMIN'
export const DELETE_ADMIN = 'DELETE_ADMIN';
export const UPDATE_ADMIN = 'UPDATE_ADMIN';
export const SET_CURRENT_ADMIN = 'SET_CURRENT_ADMIN';

export const GET_FILTER_DATA = 'GET_FILTER_DATA';
export const GET_FILTER_PRICE = 'GET_FILTER_PRICE';
export const GET_SORT_PRICE = 'GET_SORT_PRICE';



export const REG_CHECKOUT_DATA = 'REG_CHECKOUT_DATA';
export const FETCH_CHECKOUT_DATA = 'FETCH_CHECKOUT_DATA';

export const INSERT_EVENT_DATA = 'INSERT_EVENT_DATA';
export const FETCH_EVENT_DATA = 'FETCH_EVENT_DATA';
export const DELETE_EVENT_DATA = 'DELETE_EVENT_DATA';
export const UPDATE_EVENT_DATA = 'UPDATE_EVENT_DATA';






export const SUCESS_MESSAGE = 'SUCESS_MESSAGE';


export const REG_PRODUCT = 'REG_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const GET_PRODUCT_WOMAN = 'GET_PRODUCT_WOMAN';
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT';
export const FILTER_MAN_WOMAN = 'FILTER_MAN_WOMAN'


export const IS_LODDING ="IS_LODDING"
export const IS_LODDING_END ="IS_LODDING_END"

export const INSERT_LOCAL_DATA ="INSERT_LOCAL_DATA"
export const FETCH_LOCAL_DATA ="FETCH_LOCAL_DATA"

export const EDIT_DOCTOR ="EDIT_DOCTOR"
export const EDIT_STAFF ="EDIT_STAFF"



export const REG_CART = 'REG_CART';
export const GET_CART = 'GET_CART';
export const GET_CART_USER = 'GET_CART_USER'
export const  INCREMENT = "INCREMENT";
export const  DECREMENT = 'DECREMENT';
export const DELETE_CART = 'DELETE_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_CART_QUANTITY= 'UPDATE_CART_QUANTITY';
export const FILTER_CART_BY_CATA= 'FILTER_CART_BY_CATA';


export const FALSE_LOADING = 'FALSE_LOADING'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_CART_QUANTITY_CLIENT = 'UPDATE_CART_QUANTITY_CLIENT';
export const INCREMENT_CLIENT_PRODUCT = 'INCREMENT_CLIENT_PRODUCT';

export const REG_BANNER = 'REG_BANNER';
export const GET_BANNER = 'GET_BANNER';
export const DELETE_BANNER = 'DELETE_BANNER';
export const UPDATE_BANNER = 'UPDATE_BANNER';

export const REG_EMAIL = 'REG_EMAIL';
export const GET_EMAIL= 'GET_EMAIL';


// export const DELETE_SALARY = 'DELETE_SALARY';
// export const UPDATE_SALARY= 'UPDATE_SALARY';
// export const GET_SPEICL_SLARY_DATA = 'GET_SPEICL_SLARY_DATA'
// export const GET_STAFF_SALARY ='GET_STAFF_SALARY'
// export const GET_DOCTOR_SALARY = 'GET_DOCTOR_SALARY'
// export const ISPRESENT_DATA = 'ISPRESENT_DATA'



